version: '3.7'
services:
  postgresql:
    container_name: wa_challenge_postgresql
    image: bitnami/postgresql:13.4.0
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=MmksLu*R^N#xkswpzRiU2A8jhnvzX
      - POSTGRESQL_DATABASE=challenge
    restart: always

  backend:
    container_name: wa_challenge_backend
    tty: true
    build: .
    volumes:
      - ./:/backend
      - /backend/node_modules
    ports:
      - "${EXTERNAL_HTTP_PORT}:${HTTP_PORT}"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgresql
    restart: always

volumes:
  postgresql:
    driver: local
